### ISSUE TITLE
Reset button incorrectly resets time of an active task

### ISSUE THREAD

**Issue by mrCoder256** [afbora/SimpleTimeTracker#12]
I don't know how the internal logic is implemented but looks like the Reset button only resets the time that was previously "saved".

Steps to reproduce:
- Create a new task. Default time will be 0:00:00.
- Turn on this task. Wait for several seconds. For example, till 0:00:05.
- Click on Reset button.

Actual result:
- Timer wont be changed. It will show 0:00:05 and will go on ..06, ..07.
- If you turn off this task (at 0:00:07, for example) and then turn it on, wait for 2 seconds (0:00:09), then after clicking on the Reset the timer will be set to 0:00:02.

Expected result:
- If the timer is running the Reset button sets the time to 0:00:00, and then timer will continue count seconds.

Environment:
- Google Chrome Version 120.0.6099.71 (Official Build) (64-bit)
- Ubuntu 22.04.2 LTS

**Comment by afbora** [comment]
So in short, the reset should only reset the previously recorded time, not the ongoing seconds, do I understand correctly?

**Comment by mrCoder256** [comment]
@afbora, no, the Reset button should set the timer to 0. Now, if the task in turned on (active task) the button only substructs previously recorded time. If you start a timer from 0:00:00, and after 2 hours, for example, you want to reset it, then Reset button wont help you. You need to stop the timer first, and than you will able to set the timer to 0:00:00 by clicking on Reset.

**Comment by afbora** [comment]
Oh now I understand. If the timer is already 0 and started from 0, the running time is not reset.

**Comment by afbora** [comment]
Fixed in https://github.com/afbora/SimpleTimeTracker/pull/13, submitted chrome web store and will be available soon.
