### ISSUE TITLE
Stopped working on Chrome

### ISSUE THREAD

**Issue by fleps** [afbora/SimpleTimeTracker#3]
Was working fine until yesterday, today doesn't work, all tasks are gone, interacting with the buttons does nothing, disabling / enabling does nothing.

Chrome Version 119.0.6045.106
Windows 11 last release version.

**Comment by afbora** [comment]
Yes. Sorry for the issue. I've updated the chrome 119 and can reproduce the issue now. Let me check please.

**Comment by fleps** [comment]
> Yes. Sorry for the issue. I've updated the chrome 119 and can reproduce the issue now. Let me check please.

NP, thanks for taking a look!

**Comment by afbora** [comment]
> Web SQL deprecation
> 
> The Application > Web SQL section will be removed in Chrome 123 because the [Web SQL Database API](https://www.w3.org/TR/webdatabase/) [isn't maintained](https://www.w3.org/TR/webdatabase/#status-of-this-document) anymore. This version adds a warning to the section about the upcoming removal.
>
> Web SQL access in all contexts is no longer available in Chromium 119 (October 31, 2023).

https://developer.chrome.com/blog/new-in-devtools-119/#web-sql

Needs to be implemented to indexedDB or something like that. Not sure I can do soon.

**Comment by afbora** [comment]
@fleps Good news that I've almost done for IndexedDB.

**Comment by fleps** [comment]
> @fleps Good news that I've almost done for IndexedDB.

That's great, will keep an eye on the chrome webstore for the update.

Is there a way to restore the tasks once the upgrade happens or it's gone?

Cheers

**Comment by afbora** [comment]
Not sure since websql has been removed. Don't worry, I'll try a solution about migration. Sure I can't guarantee, sorry.

**Comment by afbora** [comment]
I've implemented a solution https://github.com/afbora/SimpleTimeTracker/pull/5 and will be available after v2.0.0 approved in chrome extension directory. I hope it works 🤞
